/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewsCategory = IDL.Variant({
  'entertainment' : IDL.Null,
  'business' : IDL.Null,
  'india' : IDL.Null,
  'sports' : IDL.Null,
  'gujarat' : IDL.Null,
  'world' : IDL.Null,
  'politics' : IDL.Null,
});
export const Language = IDL.Variant({
  'en' : IDL.Null,
  'gu' : IDL.Null,
  'hi' : IDL.Null,
});
export const NewsInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'isBreaking' : IDL.Bool,
  'author' : IDL.Text,
  'language' : Language,
  'imageUrl' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'category' : NewsCategory,
});
export const GalleryItem = IDL.Record({
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const NewsArticle = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishedAt' : IDL.Int,
  'isBreaking' : IDL.Bool,
  'author' : IDL.Text,
  'language' : Language,
  'imageUrl' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'category' : NewsCategory,
});
export const YoutubeVideo = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
});
export const SocialLinks = IDL.Record({
  'twitter' : IDL.Text,
  'instagram' : IDL.Text,
  'youtube' : IDL.Text,
  'facebookPage' : IDL.Text,
  'facebookProfile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContactMessage' : IDL.Func([ContactMessage], [IDL.Text], []),
  'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addYoutubeVideo' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countArticlesByCategory' : IDL.Func([NewsCategory], [IDL.Nat], []),
  'createNewsArticle' : IDL.Func([NewsInput], [IDL.Text], []),
  'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteNewsArticle' : IDL.Func([IDL.Text], [], []),
  'deleteYoutubeVideo' : IDL.Func([IDL.Text], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllYoutubeVideos' : IDL.Func([], [IDL.Vec(YoutubeVideo)], ['query']),
  'getArticlesByLanguage' : IDL.Func(
      [Language],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getBreakingNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getLatestNews' : IDL.Func([IDL.Nat], [IDL.Vec(NewsArticle)], ['query']),
  'getLiveTvUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getNewsByCategory' : IDL.Func(
      [NewsCategory],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getNewsById' : IDL.Func([IDL.Text], [NewsArticle], ['query']),
  'getPublishedBreakingArticles' : IDL.Func(
      [],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(NewsArticle)], ['query']),
  'updateLiveTvUrl' : IDL.Func([IDL.Text], [], []),
  'updateNewsArticle' : IDL.Func([IDL.Text, NewsInput], [], []),
  'updateSocialLinks' : IDL.Func([SocialLinks], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewsCategory = IDL.Variant({
    'entertainment' : IDL.Null,
    'business' : IDL.Null,
    'india' : IDL.Null,
    'sports' : IDL.Null,
    'gujarat' : IDL.Null,
    'world' : IDL.Null,
    'politics' : IDL.Null,
  });
  const Language = IDL.Variant({
    'en' : IDL.Null,
    'gu' : IDL.Null,
    'hi' : IDL.Null,
  });
  const NewsInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'isBreaking' : IDL.Bool,
    'author' : IDL.Text,
    'language' : Language,
    'imageUrl' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'category' : NewsCategory,
  });
  const GalleryItem = IDL.Record({ 'title' : IDL.Text, 'imageUrl' : IDL.Text });
  const NewsArticle = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishedAt' : IDL.Int,
    'isBreaking' : IDL.Bool,
    'author' : IDL.Text,
    'language' : Language,
    'imageUrl' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'category' : NewsCategory,
  });
  const YoutubeVideo = IDL.Record({ 'url' : IDL.Text, 'title' : IDL.Text });
  const SocialLinks = IDL.Record({
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'youtube' : IDL.Text,
    'facebookPage' : IDL.Text,
    'facebookProfile' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContactMessage' : IDL.Func([ContactMessage], [IDL.Text], []),
    'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addYoutubeVideo' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countArticlesByCategory' : IDL.Func([NewsCategory], [IDL.Nat], []),
    'createNewsArticle' : IDL.Func([NewsInput], [IDL.Text], []),
    'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteNewsArticle' : IDL.Func([IDL.Text], [], []),
    'deleteYoutubeVideo' : IDL.Func([IDL.Text], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllYoutubeVideos' : IDL.Func([], [IDL.Vec(YoutubeVideo)], ['query']),
    'getArticlesByLanguage' : IDL.Func(
        [Language],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getBreakingNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getLatestNews' : IDL.Func([IDL.Nat], [IDL.Vec(NewsArticle)], ['query']),
    'getLiveTvUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getNewsByCategory' : IDL.Func(
        [NewsCategory],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getNewsById' : IDL.Func([IDL.Text], [NewsArticle], ['query']),
    'getPublishedBreakingArticles' : IDL.Func(
        [],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(NewsArticle)], ['query']),
    'updateLiveTvUrl' : IDL.Func([IDL.Text], [], []),
    'updateNewsArticle' : IDL.Func([IDL.Text, NewsInput], [], []),
    'updateSocialLinks' : IDL.Func([SocialLinks], [], []),
  });
};

export const init = ({ IDL }) => { return []; };