/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface GalleryItem { 'title' : string, 'imageUrl' : string }
export type Language = { 'en' : null } |
  { 'gu' : null } |
  { 'hi' : null };
export interface NewsArticle {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'publishedAt' : bigint,
  'isBreaking' : boolean,
  'author' : string,
  'language' : Language,
  'imageUrl' : [] | [string],
  'isFeatured' : boolean,
  'category' : NewsCategory,
}
export type NewsCategory = { 'entertainment' : null } |
  { 'business' : null } |
  { 'india' : null } |
  { 'sports' : null } |
  { 'gujarat' : null } |
  { 'world' : null } |
  { 'politics' : null };
export interface NewsInput {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'isBreaking' : boolean,
  'author' : string,
  'language' : Language,
  'imageUrl' : [] | [string],
  'isFeatured' : boolean,
  'category' : NewsCategory,
}
export interface SocialLinks {
  'twitter' : string,
  'instagram' : string,
  'youtube' : string,
  'facebookPage' : string,
  'facebookProfile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YoutubeVideo { 'url' : string, 'title' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], string>,
  'addGalleryItem' : ActorMethod<[string, string], string>,
  'addYoutubeVideo' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countArticlesByCategory' : ActorMethod<[NewsCategory], bigint>,
  'createNewsArticle' : ActorMethod<[NewsInput], string>,
  'deleteContactMessage' : ActorMethod<[string], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteNewsArticle' : ActorMethod<[string], undefined>,
  'deleteYoutubeVideo' : ActorMethod<[string], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllNews' : ActorMethod<[], Array<NewsArticle>>,
  'getAllYoutubeVideos' : ActorMethod<[], Array<YoutubeVideo>>,
  'getArticlesByLanguage' : ActorMethod<[Language], Array<NewsArticle>>,
  'getBreakingNews' : ActorMethod<[], Array<NewsArticle>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedNews' : ActorMethod<[], Array<NewsArticle>>,
  'getLatestNews' : ActorMethod<[bigint], Array<NewsArticle>>,
  'getLiveTvUrl' : ActorMethod<[], string>,
  'getNewsByCategory' : ActorMethod<[NewsCategory], Array<NewsArticle>>,
  'getNewsById' : ActorMethod<[string], NewsArticle>,
  'getPublishedBreakingArticles' : ActorMethod<[], Array<NewsArticle>>,
  'getSocialLinks' : ActorMethod<[], SocialLinks>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchArticles' : ActorMethod<[string], Array<NewsArticle>>,
  'updateLiveTvUrl' : ActorMethod<[string], undefined>,
  'updateNewsArticle' : ActorMethod<[string, NewsInput], undefined>,
  'updateSocialLinks' : ActorMethod<[SocialLinks], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];